# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06a9756b439c2a09429980d2356ef5a3faf5b62d9c86f1264fed77f442d8b62a468baf2b3d54367624d08335bee053dc1d8a33ed54c60155bcd606527050644b

test:
  secret_key_base: 289d8bfe9524f761a61973a2343f3082b75271db07b10e5fa0ae3e39f550af8b5e97c02adc174cfc46f5b505d960403d8f20c8bae4b3cd77e9b15c5c4c422739

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
